version: '3.9'

services:
  # auth:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '5433:5432'

  postgres:
    image: postgres:15.3-bullseye
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth

  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  db_data:
  redis_data:
    driver: local
